language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.1

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

before_install:
 - apt-get install -y lib32gcc1 libc6-i386 lib32z1 lib32stdc++6
 - apt-get install -y lib32ncurses5 lib32gomp1 lib32z1-dev lib32bz2-dev
 - chmod +x gradlew
